### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by jensfr1** [omersiar/esp-rfid#126]
I tried the update via the web interface but it is not working. It always shows version 0.73. I tried updating to 0.74 and 0.75.  I have installed it on a nodemcu.

**Comment by Chopin85** [comment]
Hello the update does not work because you are using firmware.bin which is located within the bin folder(flash.bat use firmware.bin inside bin folder).
Run delete.bat in the bin folder and after replacing the firmware.bin ([firmware.zip](https://github.com/omersiar/esp-rfid/files/2170972/firmware.zip)) run flash.bat.

**Comment by jensfr1** [comment]
I was using the update from the web ui... with that file it is working from webui.

**Comment by DBR-it** [comment]
well I didn't want to start a new issue but it's more of a question is there anyway if you have multiple doors and you have these setup that you can configure it under one instead of each one that you have

**Comment by PrathikGopal** [comment]
I tested the same on webui, after i select the file it reboots and nothing happens, Same results as @jensfr1 , thanks again for your help in advance.

**Comment by omersiar** [comment]
Always use https://github.com/omersiar/esp-rfid/releases binaries, but first wait for the 0.7.7 release which will fix some bugs with versioning, then I will abandon the pre-built binary concept which is confusing.
