### ISSUE TITLE
Broken wifi, plain and simple

### ISSUE THREAD

**Issue by TCPMeta** [omersiar/esp-rfid#398]
I have tried various releases on various NodeMCU and D1 Mini modules and I get the same result. I enter my WiFi details with SSID, BSSID and password with DHCP selected and tried it with Static and it only want to run in AP Mode rather then Client Mode.
I noticed in the "Please Review Changes" window on the bottom it shows

"apip": "192.168.4.1",
"apsubnet": "255.255.255.0"

However on the top it has my WiFi info.

For giggles I tried setting the AP Mode SSID and IP to reflect on my Network's setup of 192.168.9.19 and still no luck.

**Comment by ingeninge** [comment]
I had no luck with entering my ESSID mynually in client mode. I had to:
1) choose Client mode
2) press scan
3) select Wifi Network
4) enter secret PSK
5) save and reboot.

**Comment by matjack1** [comment]
@TCPMeta @ingeninge I'm not sure if you are still interested in this project, but this problem I think is fixed with the latest `dev` build (you can find the binaries at the bottom of this page: https://github.com/esprfid/esp-rfid/actions/runs/3980992874 ).

I'm going to close now, but if you still have problems please let me know!
