### ISSUE TITLE
Flash compiledbin error

### ISSUE THREAD

**Issue by SamNitro** [omersiar/esp-rfid#54]
Hey i try to flash the compiledbin (stable and embedded-html) with windows flash.bat

After connect to 192.168.4.1 it open a site with "Not found"

What am i doing wrong

**Comment by nardev** [comment]
@SamNitro it occurred to me few times..

there is no filed in the SPIFS  ... due to some wrong settings in ld scripts it can happen that it will not properly upload code and html/js files.. once you do one, the other is wiped out..

try to comment this line in platformio.ini

build_flags = -Wl,-Tesp8266.flash.4m.ld

**Comment by SamNitro** [comment]
How I upload correctly with platformio?
Can I easy click on upload an done?

**Comment by SamNitro** [comment]
i have forget to flash 
pio run --target uploadfs

Now it run
Sorry :/
