### ISSUE TITLE
data dir missing

### ISSUE THREAD

**Issue by nardev** [omersiar/esp-rfid#64]
scripts should prepare data dir for pio  to know from where to upload the data to spiffs

**Comment by omersiar** [comment]
I think there will be no data dir at all.

Gulp script prepares web files for flashing to firmware, spiffs is no longer be used for web files anymore.

This is good because, we do not need to care about updating spiffs, user data can be preserved across firmware updates, etc

I did not test the behaviour of firmware update at this time. 

I will try to code web ui from ground up.

**Comment by omersiar** [comment]
- [ ] Test firmware update beyond 512kb

**Comment by nardev** [comment]
Tonight...

**Comment by omersiar** [comment]
Testing firmware update is not a high priority task. I think with an optimization in future we can still use OTA update, also updating from SPIFFS is an option too. So let's see what future holds.
